USE [master]
GO

/****** Object:  Database [claams]    Script Date: 1/26/2015 8:31:27 AM ******/
CREATE DATABASE [claams]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'claams', FILENAME = N'T:\Microsoft SQL Server\MSSQL11.CLAAMS\MSSQL\DATA\claams.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'claams_log', FILENAME = N'T:\Microsoft SQL Server\MSSQL11.CLAAMS\MSSQL\DATA\claams_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [claams] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [claams].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [claams] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [claams] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [claams] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [claams] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [claams] SET ARITHABORT OFF 
GO

ALTER DATABASE [claams] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [claams] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [claams] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [claams] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [claams] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [claams] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [claams] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [claams] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [claams] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [claams] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [claams] SET  DISABLE_BROKER 
GO

ALTER DATABASE [claams] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [claams] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [claams] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [claams] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [claams] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [claams] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [claams] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [claams] SET RECOVERY FULL 
GO

ALTER DATABASE [claams] SET  MULTI_USER 
GO

ALTER DATABASE [claams] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [claams] SET DB_CHAINING OFF 
GO

ALTER DATABASE [claams] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [claams] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [claams] SET  READ_WRITE 
GO

